# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kevin Maggi
email: kevin.maggi@unifi.it
description: "Kevin Maggi's personal website"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://KevinMaggi.github.io" # the base hostname & protocol for your site
twitter_username: MaKev97
github_username:  KevinMaggi

# Build settings
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-compose

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: ["_pages"]

# ---------------
# Minimal Mistakes theme configuration
# ---------------

# Skin
minimal_mistakes_skin: "default"

# Language and timezone
locale: "en-US"
timezone: Europe/Rome

# General info
# title: "Kevin Maggi" # Specified above in Jekyll configurations
title_separator: "|"
subtitle: "Personal Website"
name: "Kevin Maggi"
repository: "KevinMaggi/KevinMaggi.github.io"

# Scripts
# head_scripts:
#   -

# Appearence
# teaser: /assets/images/teaser_image.png # TODO
logo: "/assets/images/masthead_logo.png"
masthead_title: "KEVIN MAGGI"

breadcrumbs: true

# Functionalities
enable_copy_code_button: true
atom_feed:
  hide: true
search: true
search_full_content: true
search_provider: lunr
lunr:
  search_within_pages: true

# SEO
google_site_verification: "XVhYrKU7U1abnGGG4fziAk9aictckREE9F3ajHeEYlA"
bing_site_verification: "3EA7B155211A0F10071160AF3C6BAEC5"
twitter: # TODO
  username: "MaKev97"
facebook: # TODO
  publisher: "MaKev97" # ?
  username: "MaKev97"
og_image: "/assets/images/masthead_logo.png" # TODO
social:
  type: Person
  name: "Kevin Maggi"
  links:
    - "https://twitter.com/MaKev97"
    - "https://www.facebook.com/MaKev97/"
    - "https://www.instagram.com/makev97/"
    - "https://www.linkedin.com/in/makev97"
    - "https://www.researchgate.net/profile/Kevin-Maggi-4"

# Author
author:
  name: "Kevin Maggi"
  avatar: "/assets/images/bio-photo.webp"
  bio: >-
    **M.Sc.** in *Computer Engineering* <br>
    **Scholarship researcher** at [*UNIFI*](https://www.unifi.it/it) ([*STLab*](https://stlab.dinfo.unifi.it))
  location: "Prato, Italy"
  email: #TODO
  links:
    - label: "Google Scholar"
      icon: "fa-fw fa-brands fa-google-scholar"
      url: "https://scholar.google.com/citations?user=18ohcmAAAAAJ"
    - label: "ORCID"
      icon: "fa-fw fa-brands fa-orcid"
      url: "https://orcid.org/0009-0001-0651-805X"
    - label: "ResearchGate"
      icon: "fa-fw fa-brands fa-researchgate"
      url: "https://www.researchgate.net/profile/Kevin-Maggi-4"
    - label: "LinkedIn"
      icon: "fa-fw fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/makev97"
    - label: "GitHub"
      icon: "fa-fw fa-brands fa-github"
      url: "https://github.com/KevinMaggi"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KevinMaggi"
      
# Frontmatter defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      
compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

# head_scripts:
#   - /assets/js/publications.js
  